services:
  frontend:
    image: ghcr.io/wildanhanifabdillah/store-frontend:latest
    container_name: store-frontend
    env_file:
      - .env
    environment:
      NODE_ENV: production
    restart: unless-stopped
